export const adds = [
  {
    id: 1,
    span: 2,
    title: "Apply for a car loan!",
    desc: "This is a sample of a generated text",
    imageSrc: "/images/heroCards/computerScene.svg",
    buttonText: "Discover More",
    href: "#",
    bg: "#FFE0BA",
    color: "#0F2837",
    badge: null,
  },
  {
    id: 2,
    span: 1,
    title: "You have earned",
    desc: "Hooray! Way to go Mohammed!",
    imageSrc: "/images/heroCards/52. trophy-4.svg",
    buttonText: null,
    href: "#",
    bg: "#0F2837",
    color: "#fff",
    badge: { text: "Badges!", number: "20", color: "#FF9619" },
  },
  {
    id: 3,
    span: 1,
    title: "You have earned",
    desc: "Redeem and claim your rewards!",
    imageSrc: "/images/heroCards/36. people-rushing-3.svg",
    buttonText: null,
    href: "#",
    bg: "#6E1946",
    color: "#fff",
    badge: { text: "Points!", number: "1500", color: "#FAC39B" },
  },
];

export const stats = [
  {
    id: 1,
    title: "Energy",
    icon: "http://bricks.axudastudio.com/wp-content/uploads/2022/09/Energy.png",
    percentage: 45,
    color: "#A162F7",
  },
  {
    id: 2,
    title: "Range",
    icon: "http://bricks.axudastudio.com/wp-content/uploads/2022/09/Range.png",
    percentage: "157k",
    color: "#FF7E86",
  },
  {
    id: 3,
    title: "Break fluid",
    icon: "http://bricks.axudastudio.com/wp-content/uploads/2022/09/Break-fluid.png",
    percentage: 10,
    color: "#A162F7",
  },
  {
    id: 4,
    title: "Tire Wear",
    icon: "http://bricks.axudastudio.com/wp-content/uploads/2022/09/Tire-Wear.png",
    percentage: 25,
    color: "#F6CC0D",
  },
];

export const cars = [
  {
    id: 1,
    img: "/images/cars/car1.png",
    name: "Porshe 718 Cayman S",
    desc: "SUV",
    condition: "new",
    capacity: 4,
    system: "Manual",
    price: 130,
  },
  {
    id: 2,
    img: "/images/cars/car2.png",
    name: "Mini Cooper",
    desc: "Coupe",
    condition: "new",
    capacity: 4,
    system: "Automatic",
    price: 123,
  },
  {
    id: 3,
    img: "/images/cars/car3.png",
    name: "Toyota Land Cruiser",
    desc: "4x4",
    condition: "new",
    capacity: 4,
    system: "Manual",
    price: 100,
  },
  {
    id: 4,
    img: "/images/cars/car1.png",
    name: "Porshe 718 Cayman S",
    desc: "SUV",
    condition: "new",
    capacity: 4,
    system: "Manual",
    price: 130,
  },
  {
    id: 5,
    img: "/images/cars/car2.png",
    name: "Mini Cooper",
    desc: "Coupe",
    condition: "new",
    capacity: 4,
    system: "Automatic",
    price: 123,
  },
  {
    id: 6,
    img: "/images/cars/car3.png",
    name: "Toyota Land Cruiser",
    desc: "4x4",
    condition: "new",
    capacity: 4,
    system: "Manual",
    price: 100,
  },
  {
    id: 7,
    img: "/images/cars/car1.png",
    name: "Porshe 718 Cayman S",
    desc: "SUV",
    condition: "new",
    capacity: 4,
    system: "Manual",
    price: 130,
  },
  {
    id: 8,
    img: "/images/cars/car2.png",
    name: "Mini Cooper",
    desc: "Coupe",
    condition: "new",
    capacity: 4,
    system: "Automatic",
    price: 123,
  },
  {
    id: 9,
    img: "/images/cars/car3.png",
    name: "Toyota Land Cruiser",
    desc: "4x4",
    condition: "new",
    capacity: 4,
    system: "Manual",
    price: 100,
  },
];

export const bestSellingCars = [
  {
    id: 1,
    img: "/images/bestSelling/car.png",
    name: "Mini Cooper",
    recommend: 64,
    hourlyPrice: 32,
    retweet: 132,
    bg: "#E1DFA4",
  },
  {
    id: 2,
    img: "/images/bestSelling/maruti-suzuki-suzuki-swift-car-suzuki-9c5818c39cb279f9dc7f844d7769288f.png",
    name: "Porsche 911 Carrera",
    recommend: 74,
    hourlyPrice: 28,
    retweet: 130,
    bg: "#E3ECF1",
  },
  {
    id: 3,
    img: "/images/bestSelling/mini-countryman-car-bmw-mini-cooper-mini-406b2a24c59d99a8096f336f22982573.png",
    name: "Porsche 911 Carrera",
    recommend: 74,
    hourlyPrice: 28,
    retweet: 130,
    bg: "#F4E3E5",
  },
];

export const responseDelay = 1500;
